version: "3.8"

services:
  rag-server:
    image: matheusbnas/rag-server:latest
    ports:
      - "5001:5000"
    environment:
      - CORS_ORIGINS=https://chatbot-educacional.vercel.app,http://localhost:3000,http://127.0.0.1:3000,https://dna-forca-frontend.vercel.app
    volumes:
      - ./data/materials:/app/data/materials:ro
    networks:
      - network_swarm_public
    depends_on:
      - api-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-server:
    image: matheusbnas/api-server:latest
    ports:
      - "5000:5000"
    environment:
      - LOG_LEVEL=INFO
      # Adicione outras variáveis de ambiente necessárias
    volumes:
      - ./data:/app/data
    networks:
      - network_swarm_public
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: matheusbnas/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    networks:
      - network_swarm_public
    depends_on:
      - api-server


volumes:
  rag_data:
    external: true
    name: rag_data
  api_data:
    external: true
    name: api_data
  redis_data:
    external: true
    name: redis_data

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
